### ISSUE TITLE
Can't open PDF file but can chat, and create flashcard

### ISSUE THREAD

**Issue by khanhthanhdev** [zeus-12/uxie#19]
![image](https://github.com/user-attachments/assets/dc79bea9-2f49-41ac-8f95-4c6d93905e80)
I upload pdf file 50kb but it can't display and when open, the IDM automatic catch the download link

**Comment by zeus-12** [comment]
strange, the url seems to be getting blocked. 
could you try running it in incognito or a separate browser? it's probably due to some extensions.

**Comment by zeus-12** [comment]
Closing this issue due to 2 weeks of inactivity. Feel free to reopen if needed.
