### ISSUE TITLE
UploadThing callback error

### ISSUE THREAD

**Issue by darshanpatel44** [zeus-12/uxie#20]
Hi, I am setting up the project but when I upload file it get uploaded to "UploadThing" but on UploadThing Dashboad it says 
callback failed and gave this error:

Your file was uploaded, but the callback request to failed. Reason: Response 405. This is most likely due to your callback URL blocking the request.

![image](https://github.com/user-attachments/assets/67d52fd4-0781-4444-8b24-fcacb6719ebf)

Also, File is successfully uploaded to uploadthing but is not saved to my database

**Comment by zeus-12** [comment]
hey, im not near a computer rn. could you try [this?](https://discord.com/channels/966627436387266600/1102510616326967306/1313921216532189294)

**Comment by darshanpatel44** [comment]
Hey, I think I’m not part of that Discord channel. My Discord username is darshanpatel44—could you send me the invite link?

<img width="1203" alt="image" src="https://github.com/user-attachments/assets/4ff61a5f-f6c9-48b2-9dbb-f34cd4a191be">

**Comment by zeus-12** [comment]
https://discord.gg/jbjRYHFz
(uploadthing server)

**Comment by zeus-12** [comment]
Closing this issue due to 3 weeks of inactivity. Feel free to reopen if needed.
