### ISSUE TITLE
Hlo bro, I eally liked your project the only issue i'm facing is with regarding pinecone.

### ISSUE THREAD

**Issue by dheerajcl** [zeus-12/uxie#8]
I'm unable to connect to pinecone, "  tRPC failed on document.vectorise: Request failed to reach Pinecone. This can occur for reasons such as incorrect configuration (environment, project id, index name), network problems that prevent the request from being completed, or a Pinecone API outage. Check your client configuration, check your network connection, and visit https://status.pinecone.io/ to see whether any outages are ongoing.  "   .
I think the issue here is old pinecone version, the current version doesn't have environment variable but the older versions ass in this project have environment so any solutions, it would be of great help if you'd reach out.
![Screenshot from 2024-04-19 11-28-28](https://github.com/zeus-12/uxie/assets/119429314/aa76cb81-ebd1-436f-841b-e9fe6e345c4d)

**Comment by zeus-12** [comment]
You selected 768 as dimension, and Cosine as the metric right?

**Comment by dheerajcl** [comment]
I resolved it, there was a problem with versions, I upgraded pinecone package to its latest version and changed a bit of code to comply with the new version, by the way I learned a lot through this project as a rookie , great work man..!

**Comment by zeus-12** [comment]
Hey, thank you for the kind words! I'm glad to hear you were able to resolve the issue. Please feel free to raise a pull request for the changes you made to upgrade to the new version. 
Also, if you have any suggestions or improvements, please let me know. : )
